spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAMS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  url: ${SERVER_URL}