spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAMS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.id.new_generator_mappings: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    database-platform: org.hibernate.dialect.PostgreSQLDialect



# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.demo.library: DEBUG
    net.ttddyy.dsproxy.listener: DEBUG
    com.cosium.spring.data: TRACE

server:
  url: ${SERVER_URL}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packages-to-scan: com.demo.departments.demoDepartments
  paths-to-match: /api/**