apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    
  - name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200