global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scheme: http
    tls_config:
      insecure_skip_verify: true
    
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8428']